#!/bin/bash
function indent {
  while read LINE; do
    echo "  $LINE" || true
  done
}

function check_for_up {
  if ! command -v up -h > /dev/null; then
    printf '`up` is not installed.\n'
    printf 'See https://github.com/paulcsmith/up for install instructions.\n'
    exit 1
  fi
}

# http://djm.me/ask
function ask {
  # If we have a STDIN, use it, otherwise get one
  if tty >/dev/null 2>&1; then
      TTY=$(tty)
  else
      TTY=/dev/tty
  fi

  while true; do
    if [ "${2:-}" = "Y" ]; then
      prompt="Y/n"
      default=Y
    elif [ "${2:-}" = "N" ]; then
      prompt="y/N"
      default=N
    else
      prompt="y/n"
      default=
    fi

    # Ask the question (not using "read -p" as it uses stderr not stdout)
    echo -n "$1 [$prompt] "

    # Read the answer
    read REPLY < "$TTY"

    # Default?
    if [ -z "$REPLY" ]; then
      REPLY=$default
    fi

    # Check if the reply is valid
    case "$REPLY" in
      Y*|y*) return 0 ;;
      N*|n*) return 1 ;;
    esac
  done
}