#!/bin/bash

# Run db.rollback in temporary copy of 'CURRENT_VERSION' container
function rollback_db {
  printf "\n▸ Running db.rollback\n"
  docker run --rm --env-file ./Docker/lucky/migrations.env -e DATABASE_URL=postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres:5432/$POSTGRES_DB --net migrations --entrypoint lucky registry.gitlab.com/GITLAB_USER/GITLAB_REPO_NAME/lucky:$CURRENT_VERSION db.rollback | indent
}