#!/bin/sh

# build script
# Intended to be run from gitlab CI. Can be run locally thanks to `if
# CI_SERVER` variable below.
# We use REGISTRY_IMAGE, same as gitlab-ci so that we can
# tag it as the lucky image in case of others from same project in future.

if [ "$CI_SERVER" = "yes" ]; then
  export LUCKY_TAG=$CI_COMMIT_SHORT_SHA
else
  # we are building off of CI
  CI_COMMIT_REF_NAME=$(git rev-parse --abbrev-ref HEAD)
  export CI_COMMIT_REF_NAME
  export REGISTRY_IMAGE=registry.gitlab.com/GITLAB_USER/GITLAB_REPO_NAME/lucky
  LUCKY_TAG=$(git rev-parse --short=8 HEAD)
  export LUCKY_TAG
fi

docker-compose -f Docker/docker-compose.yml -f Docker/docker-compose.prod.yml build
