#!/bin/bash
# Exit if any subcommand fails
set -e
set -o pipefail

# Source lhd env variables
source ~/.lhd-env

# import functions
source "${BASH_SOURCE%/*}/functions/commons"
source "${BASH_SOURCE%/*}/functions/update_code"
source "${BASH_SOURCE%/*}/functions/rollback_db"

# Read in -s flag if provided
TYPE='add'
while getopts 's' flag; do
  case "${flag}" in
    s) TYPE='subtract';;
    *) ;;
  esac
done
shift $((OPTIND-1))

OLD_VERSION=$1

if [[ -z "$OLD_VERSION" ]]; then
  echo "Error: Must provide version argument" 1>&2
  exit 1
fi

# export for update_code
export LUCKY_TAG=$OLD_VERSION

# rollback migration runs in current container to use newest code for rollback
CURRENT_VERSION=$(git rev-parse --short=8 HEAD)
export CURRENT_VERSION

# Get timestamp of last migration in version we are rolling back to
docker pull "registry.gitlab.com/GITLAB_USER/GITLAB_REPO_NAME/lucky:$OLD_VERSION"
MIGRATION_TIMESTAMP=$(docker run --rm "registry.gitlab.com/GITLAB_USER/GITLAB_REPO_NAME/lucky:$OLD_VERSION" /home/lucky/app/script/docker/last_migration_timestamp)
export MIGRATION_TIMESTAMP

# Now it's safe to move the repo to the old version.
git checkout $OLD_VERSION

# additive migrations add to the db, so the new code relies on new stuff in the db
# and that means we have to remove that code before removing those db changes
# subtractive take away from the db, so the old code will break, so we first rollback the db
# which restores columns that current ignores, then rollback the code.
if [ "$TYPE" = "add" ]; then
  update_code
  rollback_db
else
  rollback_db
  update_code
fi

printf "\n✔ All done.\n"
