version: '3.6'
services:
  postgres:
    restart: always
    volumes:
    - db-data:/var/lib/postgresql/data
    container_name: PROJECT_NAME_postgres
    environment: 
      POSTGRES_HOST_AUTH_METHOD: "trust"
  hasura:
    ports:
    - 8080:8080
    - 9695:9695
    - 9693:9693
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:@postgres:5432/PROJECT_NAME_development
      HASURA_GRAPHQL_ADMIN_SECRET: secret
      HASURA_GRAPHQL_JWT_SECRET: '{"type": "HS256","key": "lucky_hasura_32_character_secret"}'
    container_name: PROJECT_NAME_hasura
    tty: true
    restart: always
  lucky:
    build:
      context: ../
      dockerfile: Docker/lucky/Dockerfile
    image: PROJECT_NAME_lucky:dev
    volumes:
    - ../:/home/lucky/app
    # ignores the following in the volume
    - /home/lucky/app/bin/
    - /home/lucky/app/lib/
    - /home/lucky/app/.shards/
    ports:
    - 5000:5000
    environment:
      DB_URL: postgres://postgres:@postgres:5432/PROJECT_NAME_development
      SHARDS_CACHE_PATH: /home/lucky/app/.shards
    tty: true
    container_name: PROJECT_NAME_lucky
volumes:
  db-data:
    name: PROJECT_NAME_data
