version: '3.6'
services:
  postgres:
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    volumes:
    - ~/data:/var/lib/postgresql/data
  hasura:
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB:
      HASURA_GRAPHQL_ADMIN_SECRET:
      HASURA_GRAPHQL_DATABASE_URL: "postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres:5432/$POSTGRES_DB"
      HASURA_GRAPHQL_JWT_SECRET: '{"type": "HS256","key": "$SECRET_KEY_BASE"}'
  lucky:
    build:
      context: ../
      dockerfile: Docker/lucky/Dockerfile.prod
      cache_from:
        - $REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    image: registry.gitlab.com/GITLAB_USER/GITLAB_REPO_NAME/lucky:${LUCKY_TAG}
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB:
      SECRET_KEY_BASE:
      SEND_GRID_KEY:
      APP_DOMAIN:
      LUCKY_ENV: production
      PORT: 5000
      DATABASE_URL: "postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres:5432/$POSTGRES_DB"
