#!/bin/bash
# Exit if any subcommand fails
set -e
set -o pipefail

source "${BASH_SOURCE%/*}/functions/commons"

export ORIG_METADATA_PATH="db/hasura/migrations/metadata.yaml"
export COPY_METADATA_PATH="db/hasura/migrations/metadata-copy.yaml"

function overwrite_metadata_copy {
  mv $COPY_METADATA_PATH $ORIG_METADATA_PATH
}

# make copy of local metadata, sync down hasura metadata, compare files
mv $ORIG_METADATA_PATH $COPY_METADATA_PATH
docker exec -td PROJECT_NAME_hasura /bin/hasura-cli metadata export || (overwrite_metadata_copy && exit 1)

# It might take a second for hasura to export the data and or it to sync locally.
sleep 1
until [ -f $ORIG_METADATA_PATH ]; do
  printf "hasura-metadata-sync: Waiting on Hasura.\n" | indent
  sleep 1
done

if cmp -s "$COPY_METADATA_PATH" "$ORIG_METADATA_PATH"; then
  if [[ $1 == "-v" ]]; then
    printf "✔ Hasura metadata up to date.\n"
  fi
  
else
  printf "\nHasura container metadata doesn't match local file.\n"

  if ask "Update local metadata?"; then
    printf 'Updating local metadata.yaml'
    rm $COPY_METADATA_PATH
  else
    printf "Leaving local metadata.yaml alone"
    overwrite_metadata_copy
  fi
fi
exit