
# Inspired by and based on the config mentioned here
# https://blog.callr.tech/building-docker-images-with-gitlab-ci-best-practices/
image: docker/compose:1.25.5

stages:
  - build
  - tag
  - test
  - deploy

variables:
  REGISTRY_IMAGE: registry.gitlab.com/GITLAB_USER/GITLAB_REPO_NAME/lucky
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: secret
  POSTGRES_DB: PROJECT_NAME_test
  SECRET_KEY_BASE: lucky_hasura_32_character_secret
  HASURA_GRAPHQL_ADMIN_SECRET: secret
  SEND_GRID_KEY: unused
  APP_DOMAIN: localhost

services:
  - docker:dind # docker-in-docker, makes `docker` and `docker-compose` commands available

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

Build:
  stage: build
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /no-build/
      - $CI_COMMIT_MESSAGE =~ /tag-only/
      - $CI_COMMIT_MESSAGE =~ /test-only/
      - $CI_COMMIT_MESSAGE =~ /deploy-only/
  script:
    # fetches the latest image on the branch, does not fail if not found
    - docker pull $REGISTRY_IMAGE:$CI_COMMIT_REF_NAME || true
    - script/build
    - docker push $REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

Test:
  stage: test
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /no-test/
      - $CI_COMMIT_MESSAGE =~ /build-only/
      - $CI_COMMIT_MESSAGE =~ /tag-only/
      - $CI_COMMIT_MESSAGE =~ /deploy-only/
  script:
    - script/test

Deploy staging:
  stage: deploy
  only:
    - staging
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /no-deploy/
      - $CI_COMMIT_MESSAGE =~ /build-only/
      - $CI_COMMIT_MESSAGE =~ /tag-only/
      - $CI_COMMIT_MESSAGE =~ /test-only/
  script:
    - script/ci_deploy staging

Deploy production:
  stage: deploy
  only:
    - master
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /no-deploy/
      - $CI_COMMIT_MESSAGE =~ /build-only/
      - $CI_COMMIT_MESSAGE =~ /tag-only/
      - $CI_COMMIT_MESSAGE =~ /test-only/
  script:
    - script/ci_deploy production
